version: '3.4'

services:
  publicsharing.api:
    image: ${DOCKER_REGISTRY-}publicsharingapi
    build:
      context: .
      dockerfile: PublicSharing.Api/Dockerfile
    depends_on:
      - mongodb
      - redis
      - prometheus
    ports:
      - "8001:80"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  mongodb-data:
  redis-data:
  prometheus-data: